### ISSUE TITLE
Clarify if dynamic nonopaque direct studies should use the blk modifier

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/radiance-folder-structure#14]
Right now, the [dynamic opaque folder](https://github.com/ladybug-tools/radiance-folder-structure/tree/master/project_folder/model/dynamic/opaque) states that "we can use the same file with black materials for direct studies." I am guessing that this means the direct version of the dynamic opaque geometry is supposed to use the blk modifier by default, which seems ok.

However, the way that [the dynamic nonopaque page](https://github.com/ladybug-tools/radiance-folder-structure/tree/master/project_folder/model/dynamic/nonopaque) is set up, it seems that the same logic should be applied here but, thinking about this more, this does not make sense. You would probably want the direct study with nonopaque geometry to use the same modifier as the given state by default (not a black material). So, if the direct file is not a black material, should there be a separate `"black"` key for dynamic nonopaque geometry like there is for dynamic apertures? Or will we never have a need to run isolation studies with dynamic shades and so we can still leave out the `"black"` key?

**Comment by mostaphaRoudsari** [comment]
Good question. Your assumption is correct that the non-opaque will stay non-opaque all the time. I think you are right that we can remove the 'black' key in this case. I cannot think of a case that it can be useful.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/radiance-folder-structure/pull/16
